apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: saas-operator
    control-plane: controller-manager
  name: saas-operator-controller-manager-metrics-monitor
spec:
  endpoints:
  - path: /metrics
    port: metrics
    scheme: http
  selector:
    matchLabels:
      app.kubernetes.io/name: saas-operator
      control-plane: controller-manager
