apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: saas-operator
  name: saas-operatormappingservice-admin-role
rules:
- apiGroups:
  - saas.3scale.net
  resources:
  - mappingservices
  verbs:
  - '*'
- apiGroups:
  - saas.3scale.net
  resources:
  - mappingservices/status
  verbs:
  - get
