apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: saas-operatormanager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - patch
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - autoscaling
  resources:
  - horizontalpodautoscalers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - external-secrets.io
  resources:
  - externalsecrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - grafana.integreatly.org
  resources:
  - grafanadashboards
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - marin3r.3scale.net
  resources:
  - envoyconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - monitoring.coreos.com
  resources:
  - podmonitors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - saas.3scale.net
  resources:
  - apicasts
  - autossls
  - backends
  - corsproxies
  - echoapis
  - mappingservices
  - redisshards
  - sentinels
  - shardedredisbackups
  - systems
  - twemproxyconfigs
  - zyncs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - saas.3scale.net
  resources:
  - apicasts/finalizers
  - autossls/finalizers
  - backends/finalizers
  - corsproxies/finalizers
  - echoapis/finalizers
  - mappingservices/finalizers
  - redisshards/finalizers
  - sentinels/finalizers
  - shardedredisbackups/finalizers
  - systems/finalizers
  - twemproxyconfigs/finalizers
  - zyncs/finalizers
  verbs:
  - update
- apiGroups:
  - saas.3scale.net
  resources:
  - apicasts/status
  - autossls/status
  - backends/status
  - corsproxies/status
  - echoapis/status
  - mappingservices/status
  - redisshards/status
  - sentinels/status
  - shardedredisbackups/status
  - systems/status
  - twemproxyconfigs/status
  - zyncs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - tekton.dev
  resources:
  - pipelines
  - tasks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
