resources:
  - https://raw.githubusercontent.com/tektoncd/pipeline/refs/tags/v1.0.0/config/300-crds/300-pipeline.yaml
  - https://raw.githubusercontent.com/tektoncd/pipeline/refs/tags/v1.0.0/config/300-crds/300-task.yaml

patches:
  - target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
    patch: |-
      - op: remove
        path: /spec/conversion