name: catalog

on:
  push:
    branches:
      - main
    paths:
      - catalog/saas-operator/stable-channel.yaml
  workflow_dispatch:

permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Enable QEMU
        run: sudo apt update && sudo apt install qemu-user-static

      - name: Login to quay.io/3scale
        uses: redhat-actions/podman-login@v1
        with:
          registry: quay.io
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build & push catalog
        run: make catalog-publish
